### ISSUE TITLE
Typo in motd_text_default.txt and motd_default.txt

### ISSUE THREAD

**Issue by tryzombie501** [FriskTheFallenHuman/css-community#11]
**Describe the bug**
The text window says "Sommunity" which should be "Community"

**To Reproduce**
1. Start a new match and view the motd window.

**Expected behavior**
The window should say:

> Welcome to Counter-Strike Source Community
> Play nice.
> 
> Our map rotation is:
> - Italy
> - Dust
> - Aztec
> - Cobble
> - Office Complex
> - Chateau
> - Dust II
> - Piranesi
> - Havana
> - Prodigy
> - Compound
> - Train
> - Tides
> - Port
> - Inferno
> - Assault
> - Nuke
> - Militia

**Screenshots**
None

**Comment by FriskTheFallenHuman** [comment]
Fixed Thanks!
