### ISSUE TITLE
Cant load client dll

### ISSUE THREAD

**Issue by brokeDude2901** [FriskTheFallenHuman/css-community#3]
Is it me using the wrong 2013 sdk version or sth wrong? no matter what they refuse to load dll

**Comment by FriskTheFallenHuman** [comment]
copy the **fmod.dll** from [src/thirdparty/fmod/lib](https://github.com/FriskTheFallenHuman/css-community/tree/master/mp/src/thirdparty/fmod/lib) to mod's bin folder

**Comment by FriskTheFallenHuman** [comment]
or if you don't have css intall it

**Comment by FriskTheFallenHuman** [comment]
But, are you sure you have **Counter Strike Source installed**?

**Comment by brokeDude2901** [comment]
> 
> 
> copy the **fmod.dll** from [src/thirdparty/fmod/lib](https://github.com/FriskTheFallenHuman/css-community/tree/master/mp/src/thirdparty/fmod/lib) to mod's bin folder

this solve the problem!
